name: DeployToS3

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  
  build:
   
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      - run: aws s3 sync ./website s3://profile.cloudofthings.net
  
   
